image: cirrusci/flutter:latest

pipelines:
  default:
    - step:
        name: Build and Test Flutter App
        caches:
          - flutter
        script:
          - flutter pub get
          - flutter test
          # Optional: Add build command if needed
          # - flutter build apk --release
