image: ghcr.io/cirruslabs/flutter:3.29

definitions:
  caches:
    flutter: ~/.pub-cache

pipelines:
  default:
    - step:
        name: Build and Test Flutter App
        caches:
          - flutter
        script:
          - flutter pub get
          - flutter test
